#indica la version de Docker Compose utilizada
version: '3.9'
#Bloque de servicios, indica los contenedores a utilizar.
services:
  weba:       #nombre del servicio
    #    build: ./practica-4
    image: radf0001/practica-6-app-web:latest
    env_file: #Indica el parametro para
      - .env
    environment:    #variable de ambiente
      - NOMBRE_APP=$AMBIENTE
      - server.port=8080
    expose:
      - 8080
    restart: always
    networks:    #red para conectar los equipos.
      - red-app
    depends_on:   #indica que primero debe subir los servicios indicados.
      base-datos-app-web:
        condition: service_healthy

  webb: #nombre del servicio
    #    build: ./practica-4
    image: radf0001/practica-6-app-web:latest
    env_file: #Indica el parametro para
      - .env
    environment: #variable de ambiente
      - NOMBRE_APP=$AMBIENTE
      - server.port=8081
    expose:
      - 8081
    restart: always
    networks: #red para conectar los equipos.
      - red-app
    depends_on: #indica que primero debe subir los servicios indicados.
      base-datos-app-web:
        condition: service_healthy
        
  base-datos-app-web:
    image: mysql:5.6.45
    ports:
      - ${PUERTO_DB}:${DB_PORT}
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_USER=$DB_USER
      - MYSQL_DATABASE=$DB_NAME
    volumes:   #volumen de datos utilizado.
      - mi-volumen-bd:${DB_UBI}
    networks:
      - red-app
    healthcheck:
      test: [ "CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'db', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 5s
      retries: 5

  haproxy:
    environment:
      - CERT1=aws.playdomtv.me
      - EMAIL=radf0001@ce.pucmm.edu.do
      - STAGING=false
    volumes:
      - ./haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg
    links:
      - weba
      - webb
    networks:
      - red-app
    ports:
      - '80:80'
      - '443:443'
    image: 'ghcr.io/tomdess/docker-haproxy-certbot:master'

networks:  #bloque para las redes
  red-app:   #indicando la red definida

volumes: #Bloque para definir los volumenes
  mi-volumen-bd:
